language: node_js
sudo: false
node_js:
  - '7'
  - '6'
  - '4'

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install: yarn --frozen-lockfile
